### PR TITLE
Fix atari core unzip path

### PR DESCRIPTION
**Pull request by stephenegriffin**
should unzip Atari core into coresPath with the others

### CODE REVIEW

**Comment by Francommit** [comment]
Could you get this working? I was struggling with the retroarch core?

**Comment by stephenegriffin** [comment]
Well - right now my big problem is the version of emulationstation that comes from choco - it doesn't seem to want to work on my machine. So I run your script to get everything installed, then uninstall emulationstation from apps and features (keeping user settings, which choco doesn't offer), then install from emulationstation.org.

*After that*, yes, this fix did set up the core for Atari properly.

**Comment by Francommit** [comment]
Ahhhh I see. Odd the chocolatey package didn't work. Can I ask what version of windows are you running? 64 bit as well I'm assuming?

**Comment by Francommit** [comment]
I think I might consider setting up ES without the chocolatey package didn't know this was an issue for people. OR maybe just throwing on the force flag to the installer will cover most cases?

**Comment by stephenegriffin** [comment]
Yeah-  the choco thing has me a bit confused - from what I've dug up so far they should be the same builds. I'm on Win 10 64, but I think you may be on to something about 64 v 32 bit builds. I've got some testing to do...

**Pull request merged**
